# IBM DB2 — DB2 方言族，默认端口 50000
spring.datasource.url= jdbc:db2://localhost:50000/testdb
spring.datasource.username= db2inst1
spring.datasource.password= 123456
mybatis.mapper-locations= resources/mapper
