spring.datasource.url= jdbc:kingbase8://localhost:54321/testdb
spring.datasource.username= system
spring.datasource.password= 123456
#connection pool settings
mybatis.mapper-locations= resources/mapper
