# openGauss（华为开源，PostgreSQL 兼容）
spring.datasource.url= jdbc:opengauss://localhost:5432/testdb
spring.datasource.username= root
spring.datasource.password= 123456
mybatis.mapper-locations= resources/mapper
