package types

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"github.com/bnulwh/mybatis-go/log"
	"github.com/bnulwh/mybatis-go/types/sqlfragment"
	"github.com/bnulwh/mybatis-go/utils"
)

// xml2go：XML Mapper 逆向代码生成 —— 从既有 MyBatis / MyBatis-Plus XML 生成
// 可直接编译运行的 Go 代码（cmd/generator 的强化替代）：
//
//	<output>/models/<模型短名>.go   模型 struct（db tag 带列名与 pk/logic/version 元数据，
//	                                 json tag、TableName() 方法）
//	<output>/mapper/<Mapper短名>.go Mapper 代理 struct（orm.BaseMapper + 函数字段 +
//	                                 init 注册模型与 Mapper + sync.Once 单例 getter）
//
// 与旧 generator 的差异：
//   - 参数签名精确化：struct 参数为指针接收者 *models.X（P1 ID 回填/自动填充要求可寻址）；
//     无 parameterType 的语句按占位符逐个生成具名 interface{} 参数（与 1.2 按位绑定对齐）；
//     selectPage 固定 *orm.PageParam / *orm.Page；MP insertBatch 生成 []*models.X；
//   - 返回类型与注册期校验（orm.ReturnType.checkSql）逐条对齐：resultMap → []models.X、
//     resultType=long/int 等 → []标量、resultType=map/pojo（未注册模型）→ []map、
//     resultType=业务模型且已生成 → []models.X（M-04 运行期模型转换路径）；
//   - 模型带 db tag 元数据（pk / logic=deleted|del_flag / version），RegisterModel 后
//     经 SetModelStructureProvider 反哺 MP 内置 CRUD 生成；
//   - 跨 Mapper 模型去重、引用未生成模型的语句跳过并记录原因（产物保证可编译）；
//   - 全部产物 gofmt + go/parser 语法校验（约定 4.2）。
//
// 已知边界（同运行时限制）：
//   - 跨 Mapper 的嵌套 resultMap 引用（如 resultMap="SysRoleMapper.RoleResult"）
//     静态不可解析，字段退化为 interface{}（运行期仍按全局 resultMap 正常转换）；
//   - ${} 注入占位符同样计入参数槽，生成 interface{} 具名参数（注意 SQL 注入风险）。

// Xml2GoOptions xml2go 生成选项。
type Xml2GoOptions struct {
	// OutputDir 输出根目录，内含 models/ 与 mapper/ 两个子目录，默认 gen
	OutputDir string
	// ModulePrefix 生成包的模块导入路径前缀（如 github.com/xxx/app），
	// models 导入路径为 <ModulePrefix>/models；留空时退化为裸导入 "models"（GOPATH 兼容）
	ModulePrefix string
	// SkipMP 跳过 MyBatis-Plus 内置 CRUD（insert/deleteById/... /insertBatch）字段
	SkipMP bool
}

// Xml2GoStats 单个 Mapper 的生成统计。
type Xml2GoStats struct {
	Mapper     string
	MapperFile string
	Models     int // 本 Mapper init() 注册的模型数
	Functions  int
	Skipped    []QuerierSkip
}

// Xml2GoResult 批量生成结果：模型文件清单 + 逐 Mapper 统计。
type Xml2GoResult struct {
	ModelFiles []string
	Stats      []*Xml2GoStats
}

// xml2GoShared 跨 Mapper 共享生成状态。
type xml2GoShared struct {
	Models      map[string]*ResultMap   // 模型短名 → 首个 resultMap（去重）
	Owner       map[string]*SqlMapper   // 模型短名 → 所属 Mapper（渲染时取其 NamedMaps）
	Order       []string                // 模型首现序（保证输出稳定）
	MapperFiles map[string]string       // Mapper 短名 → 已生成文件（同名冲突检测）
}

// GenerateXml2GoFiles 为全部 Mapper 生成 models + mapper 两套 Go 文件。
// 返回生成结果（含跳过原因），供调用方（cmd/xml2go）打印报告。
func (in *SqlMappers) GenerateXml2GoFiles(opt *Xml2GoOptions) (*Xml2GoResult, error) {
	if opt == nil {
		opt = &Xml2GoOptions{}
	}
	if opt.OutputDir == "" {
		opt.OutputDir = "gen"
	}
	modelsDir := filepath.Join(opt.OutputDir, "models")
	mapperDir := filepath.Join(opt.OutputDir, "mapper")
	if err := utils.MakeDirAll(modelsDir); err != nil {
		return nil, err
	}
	if err := utils.MakeDirAll(mapperDir); err != nil {
		return nil, err
	}
	shared := &xml2GoShared{
		Models:      map[string]*ResultMap{},
		Owner:       map[string]*SqlMapper{},
		MapperFiles: map[string]string{},
	}
	result := &Xml2GoResult{}
	// 1. 全局收集业务模型（跨 Mapper 去重，首个 resultMap 生效）
	for i := range in.Mappers {
		mp := &in.Mappers[i]
		for _, rm := range mp.Maps {
			if rm == nil || rm.TypeName == "" {
				continue
			}
			sn := GetShortName(rm.TypeName)
			if sn == "" || IsJdkType(sn) {
				continue
			}
			if _, ok := shared.Models[sn]; ok {
				log.Warnf("xml2go: 模型 %v 重复定义（namespace %v），沿用首个 resultMap", sn, mp.Namespace)
				continue
			}
			shared.Models[sn] = rm
			shared.Owner[sn] = mp
			shared.Order = append(shared.Order, sn)
		}
	}
	// 2. 渲染模型文件
	for _, sn := range shared.Order {
		rm := shared.Models[sn]
		content := renderXml2GoModel(rm, shared.Owner[sn].NamedMaps)
		file := filepath.Join(modelsDir, fmt.Sprintf("%s.go", sn))
		if err := os.WriteFile(file, []byte(content), 0640); err != nil {
			return result, err
		}
		gofmtFile(file) // 4.2：生成物统一 gofmt
		if err := ParseQuerierFileSyntax(file); err != nil {
			return result, fmt.Errorf("model file %v syntax invalid: %w", file, err)
		}
		result.ModelFiles = append(result.ModelFiles, file)
	}
	// 3. 逐 Mapper 生成代理文件
	for i := range in.Mappers {
		mp := &in.Mappers[i]
		st := mp.generateXml2GoMapperFile(mapperDir, opt, shared)
		if st != nil {
			result.Stats = append(result.Stats, st)
		}
	}
	return result, nil
}

// renderXml2GoModel 渲染单个模型文件内容：struct（db/json tag）+ TableName()。
func renderXml2GoModel(rm *ResultMap, namedMaps map[string]*ResultMap) string {
	var buf bytes.Buffer
	sname := GetShortName(rm.TypeName)
	buf.WriteString("// Code generated by mybatis-go cmd/xml2go from XML mapper resultMap. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "// 源: resultMap %v (type: %v)\n\n", rm.Id, rm.TypeName)
	buf.WriteString("package models\n\n")
	var fields bytes.Buffer
	seen := map[string]bool{}
	for _, item := range rm.Results {
		if item == nil || item.Property == "" {
			continue // discriminator 等无 property 项不生成字段
		}
		fname := UpperFirst(item.Property)
		if seen[fname] {
			log.Warnf("xml2go: 模型 %v 字段 %v 重复，跳过后续定义", sname, item.Property)
			continue
		}
		seen[fname] = true
		typ := item.golangType(namedMaps)
		fmt.Fprintf(&fields, "\t%s %s `db:\"%v\" json:\"%v\"`\n", fname, typ, xml2GoDbTag(item), item.Property)
	}
	if strings.Contains(fields.String(), "time.Time") {
		buf.WriteString("import \"time\"\n\n")
	}
	fmt.Fprintf(&buf, "// %v 源自 resultMap %v。\n", sname, rm.Id)
	fmt.Fprintf(&buf, "type %v struct {\n%v}\n\n", sname, fields.String())
	// 字段名与 TableName() 方法冲突时跳过方法；
	// 方法体与 orm.ParseModelInfo 的默认表名推导完全一致，跳过零行为损失
	if seen["TableName"] {
		log.Warnf("xml2go: 模型 %v 已存在 TableName 字段，跳过 TableName() 方法（表名走 orm 默认推导）", sname)
	} else {
		fmt.Fprintf(&buf, "// TableName 表名（type 短名去 Model 后缀 + camelCase → snake_case）。\n")
		fmt.Fprintf(&buf, "func (%v) TableName() string {\n\treturn %q\n}\n", sname, camelToSnake(strings.TrimSuffix(sname, "Model")))
	}
	return buf.String()
}

// xml2GoDbTag 生成字段 db tag：
// id/result → 列名（缺省 camelToSnake(property)），主键追加 ,pk，
// 逻辑删除列（deleted/del_flag 约定）追加 ,logic，乐观锁列（version）追加 ,version；
// association/collection → "-"（由关联查询填充，不参与列扫描）。
func xml2GoDbTag(item *ResultItem) string {
	switch item.Kind {
	case ResultItemKindId, ResultItemKindResult:
		col := item.Column
		if col == "" {
			col = camelToSnake(item.Property)
		}
		tag := col
		if item.PrimaryKey {
			tag += ",pk"
		}
		low := strings.ToLower(col)
		if low == "deleted" || low == "del_flag" {
			tag += ",logic"
		}
		if low == "version" {
			tag += ",version"
		}
		return tag
	default:
		return "-"
	}
}

// generateXml2GoMapperFile 为单个 Mapper 渲染代理文件并写盘。
func (in *SqlMapper) generateXml2GoMapperFile(dir string, opt *Xml2GoOptions, shared *xml2GoShared) *Xml2GoStats {
	sname := GetShortName(in.Namespace)
	stats := &Xml2GoStats{Mapper: in.Namespace}
	if sname == "" {
		stats.Skipped = append(stats.Skipped, QuerierSkip{Id: in.Namespace, Reason: "namespace 无法推导 Mapper 短名"})
		return stats
	}
	if prev, ok := shared.MapperFiles[sname]; ok {
		log.Errorf("xml2go: Mapper 短名 %v 冲突（%v 已生成），跳过 %v", sname, prev, in.Namespace)
		stats.Skipped = append(stats.Skipped, QuerierSkip{Id: sname, Reason: fmt.Sprintf("同名 Mapper 已生成（%v），跳过", prev)})
		return stats
	}
	// MP 内置 insertBatch 的元素模型：本 Mapper 首个可推导表结构的 resultMap 模型
	primary := ""
	if _, rm := buildTableStructureFromResultMap(in); rm != nil {
		primary = GetShortName(rm.TypeName)
	}

	var fields bytes.Buffer
	var register []string
	regSeen := map[string]bool{}
	addReg := func(sn string) {
		if sn == "" || shared.Models[sn] == nil || regSeen[sn] {
			return
		}
		regSeen[sn] = true
		register = append(register, sn)
	}
	// 本 Mapper 的业务 resultMap 模型全部注册
	for _, rm := range in.Maps {
		if rm != nil {
			addReg(GetShortName(rm.TypeName))
		}
	}
	seenFields := map[string]bool{}
	for _, fn := range in.Functions {
		if fn == nil {
			continue
		}
		if opt.SkipMP && xml2GoIsMPBuiltin(fn.Id) {
			continue
		}
		fname := UpperFirst(sanitizeQuerierArgName(fn.Id))
		lk := strings.ToLower(fname)
		if seenFields[lk] {
			stats.Skipped = append(stats.Skipped, QuerierSkip{Id: fn.Id, Reason: "函数字段名冲突（大小写不敏感），跳过后续定义"})
			continue
		}
		params, rets, skip := xml2GoSignature(fn, primary, shared)
		if skip != nil {
			stats.Skipped = append(stats.Skipped, *skip)
			continue
		}
		seenFields[lk] = true
		fmt.Fprintf(&fields, "\t%v func(%v) (%v)\n", fname, params, rets)
		stats.Functions++
		if fn.Param.Need && !fn.Param.AutoDerive && fn.Param.Type == StructSqlParam {
			addReg(GetShortName(fn.Param.TypeName))
		}
		if fn.Result.ResultM != nil {
			addReg(GetShortName(fn.Result.ResultM.TypeName))
		}
	}
	stats.Models = len(register)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by mybatis-go cmd/xml2go from XML mapper. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "// 源: %v (namespace: %v)\n\n", filepath.Base(in.Filename), in.Namespace)
	buf.WriteString("package mapper\n\n")
	needModels := len(register) > 0 || strings.Contains(fields.String(), "models.")
	needTime := strings.Contains(fields.String(), "time.Time")
	buf.WriteString("import (\n\t\"sync\"\n\n\t\"github.com/bnulwh/mybatis-go/orm\"\n")
	if needModels {
		if opt.ModulePrefix != "" {
			fmt.Fprintf(&buf, "\n\tmodels %q\n", strings.TrimSuffix(opt.ModulePrefix, "/")+"/models")
		} else {
			buf.WriteString("\n\tmodels \"models\"\n")
		}
	}
	if needTime {
		buf.WriteString("\n\t\"time\"\n")
	}
	buf.WriteString(")\n\n")
	fmt.Fprintf(&buf, "// %v XML Mapper 代理结构体（函数字段由 orm 反射注入）。\n", sname)
	fmt.Fprintf(&buf, "type %v struct {\n\torm.BaseMapper\n%v}\n\n", sname, fields.String())
	fmt.Fprintf(&buf, "var (\n\tg%v *%v\n\tg%vOnce sync.Once\n)\n\n", sname, sname, sname)
	buf.WriteString("func init() {\n")
	for _, sn := range register {
		fmt.Fprintf(&buf, "\torm.RegisterModel(new(models.%v))\n", sn)
	}
	fmt.Fprintf(&buf, "\torm.RegisterMapper(new(%v))\n", sname)
	buf.WriteString("}\n\n")
	fmt.Fprintf(&buf, "// Get%v 取 Mapper 单例（首次调用时由 orm 注入函数字段代理）。\n", sname)
	fmt.Fprintf(&buf, "func Get%v() *%v {\n\tg%vOnce.Do(func() {\n\t\tg%v = orm.NewMapperPtr(%q).(*%v)\n\t})\n\treturn g%v\n}\n",
		sname, sname, sname, sname, sname, sname, sname)

	file := filepath.Join(dir, fmt.Sprintf("%s.go", sname))
	if err := os.WriteFile(file, buf.Bytes(), 0640); err != nil {
		log.Errorf("xml2go: 写 Mapper 文件 %v 失败: %v", file, err)
		stats.Skipped = append(stats.Skipped, QuerierSkip{Id: sname, Reason: fmt.Sprintf("写盘失败: %v", err)})
		return stats
	}
	gofmtFile(file) // 4.2：生成物统一 gofmt
	if err := ParseQuerierFileSyntax(file); err != nil {
		log.Errorf("xml2go: Mapper 文件 %v 语法校验失败: %v", file, err)
		stats.Skipped = append(stats.Skipped, QuerierSkip{Id: sname, Reason: fmt.Sprintf("语法校验失败: %v", err)})
		return stats
	}
	shared.MapperFiles[sname] = file
	stats.MapperFile = file
	return stats
}

// xml2GoSignature 推导单个语句的函数字段签名（参数 + 返回值）；
// 无法静态化（引用未生成模型等）时返回跳过原因。
// 签名与 orm 注册期校验（ParamType/ReturnType.checkSql）逐条对齐。
func xml2GoSignature(fn *SqlFunction, primary string, shared *xml2GoShared) (string, string, *QuerierSkip) {
	var params []string
	switch {
	case fn.Id == MPSelectPageID:
		params = append(params, "page *orm.PageParam")
	case fn.Id == MPInsertBatchID && primary != "":
		// MP insertBatch：单切片参数 → 运行期 Slice 路径渲染 foreach（P1-4）
		params = append(params, "models []*models."+primary)
	case !fn.Param.Need:
		// 无参语句
	case fn.Param.AutoDerive:
		// 无显式 parameterType：foreach 场景单 map 按名取数最稳；
		// 其余按占位符逐个生成具名 interface{} 参数（与 1.2 按位绑定一致）
		if sqlfragment.ContainsForEach(fn.Items) {
			params = append(params, "param map[string]interface{}")
		} else {
			for _, slot := range fn.Param.Slots {
				params = append(params, sanitizeQuerierArgName(slot)+" interface{}")
			}
			if len(params) == 0 {
				params = append(params, "param interface{}")
			}
		}
	default:
		switch fn.Param.Type {
		case StructSqlParam:
			sn := GetShortName(fn.Param.TypeName)
			if shared.Models[sn] == nil {
				return "", "", &QuerierSkip{Id: fn.Id, Reason: fmt.Sprintf("parameterType=%v 未生成对应模型（缺少 resultMap 定义）", fn.Param.TypeName)}
			}
			// 指针接收者：P1 ID 回填 / 自动填充要求字段可寻址
			params = append(params, "model *models."+sn)
		case MapSqlParam:
			params = append(params, "param map[string]interface{}")
		case SliceSqlParam:
			params = append(params, "items []interface{}")
		default: // BaseSqlParam 标量
			pt := toGolangType(fn.Param.TypeName)
			if sqlfragment.ContainsForEach(fn.Items) {
				// parameterType=Long + foreach（批量 in）：运行期按 Slice 路径渲染
				params = append(params, "ids []"+pt)
			} else {
				pname := "arg"
				if len(fn.Param.Slots) > 0 {
					pname = sanitizeQuerierArgName(fn.Param.Slots[0])
				}
				params = append(params, pname+" "+pt)
			}
		}
	}
	var rets string
	switch fn.Type {
	case UpdateFunction, InsertFunction, DeleteFunction:
		rets = "int64, error"
	default: // SelectFunction
		switch {
		case fn.Id == MPSelectPageID:
			rets = "*orm.Page, error"
		case fn.Result.ResultM != nil:
			sn := GetShortName(fn.Result.ResultM.TypeName)
			if IsJdkType(sn) {
				return "", "", &QuerierSkip{Id: fn.Id, Reason: fmt.Sprintf("resultMap=%v 类型为 JDK 基础类型，无法生成模型返回", fn.Result.ResultM.Id)}
			}
			rets = "[]models." + sn + ", error"
		case fn.Result.ResultT == nil:
			rets = "[]int64, error"
		case fn.Result.ResultT.Kind() == reflect.Map:
			// M-04：resultType 指向已注册业务模型 → 运行期按模型转换
			tn := GetShortName(fn.Result.ResultTypeName)
			if fn.Result.ResultTypeName != "" && !IsJdkType(tn) && shared.Models[tn] != nil {
				rets = "[]models." + tn + ", error"
			} else {
				rets = "[]map[string]interface{}, error"
			}
		default:
			// 标量返回直接取 reflect.Type 的 Go 原生名（与注册期 SameTypeCheck 严格一致）
			rets = "[]" + fn.Result.ResultT.String() + ", error"
		}
	}
	return strings.Join(params, ", "), rets, nil
}

// xml2GoIsMPBuiltin 判断语句 ID 是否为 MyBatis-Plus 内置 CRUD 方法名。
func xml2GoIsMPBuiltin(id string) bool {
	for _, b := range mpBuiltinIDs {
		if strings.EqualFold(id, b) {
			return true
		}
	}
	return false
}
