# GaussDB（华为云，PostgreSQL 兼容）
spring.datasource.url= jdbc:gaussdb://localhost:5432/testdb
spring.datasource.username= root
spring.datasource.password= 123456
mybatis.mapper-locations= resources/mapper
