# MS SQL Server（默认端口 1433）
spring.datasource.url= jdbc:sqlserver://localhost:1433/testdb
spring.datasource.username= sa
spring.datasource.password= 123456
spring.datasource.max-idle= 100
spring.datasource.max-open= 100
spring.datasource.max-timeout=100
mybatis.mapper-locations= resources/mapper
